apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: interop
  labels:
    app: redis
spec:
  ports:
    - name: redis-port
      protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
  clusterIP: None
