apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-service-deploy
  namespace: interop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: vote-service-container
          image: <ACR login server>/<name-of-container>:<tag-name>
          ports:
            - containerPort: 50001
          env:
          - name: REDIS_HOST
            value: "<service-name>.<namespace>.svc.cluster.local"
          - name: REDIS_PORT
            value: "6379"
          - name: CANDIDATE_1_NAME
            value: "Cats"
          - name: CANDIDATE_2_NAME
            value: "Dogs"